### ISSUE TITLE
UserPanel -> $auth->user()

### ISSUE THREAD

**Issue by molbi** [recca0120/Laravel-Tracy#1]
Hi, Iam using Laravel 5.1 and their Auth component. But after login, i still have Guest as user in UserPanel. When i have tried find, where problem is. I figured out, that $auth->user() return Exception
"ReflectionException #-1,Class hash does not exist".  It looks like, that Laravel Hasher isnt initialized.

**Comment by recca0120** [comment]
Hi molbi,
sorry about that i see this issue just right now....
this bug is be fixed
thanks for your response...
