### ISSUE TITLE
Tracy dump() and barDump() methods don't print the desired variables

### ISSUE THREAD

**Issue by TeeJay-net** [recca0120/laravel-tracy#13]
Hi,
the title is obvious but still - neither of these var dump static methods work for me.

This code
```
Debugger::barDump('foo');
Debugger::dump('bar');
```
prints exactly nothing. In Nette, it works well.

Are you planning support of these essentials methods? :)
Thanks.

**Comment by recca0120** [comment]
Hi

there are two way to call barDump and dump

use static method
```php
\Tracy\Debugger::dump('foo');
\Tracy\Debugger::barDump('bar');
```

or

```php
dump('foo'); // maybe not working, if you install symfony/var-dump
bdump('bar');
```


[Tracy shortcuts function](https://github.com/nette/tracy/blob/master/src/shortcuts.php)

**Comment by recca0120** [comment]
or you can try this

```php
use Tracy\Debugger;

Debugger::barDump('foo');
```

**Comment by TeeJay-net** [comment]
Thank you!
For some reason, only `dump('foo')` works. None of the other methods. It doesn't throw any errors, there is just no output from the functions calls.

This code (called in a controller)...
```php
use Tracy\Debugger;

bdump('foo');
\Tracy\Debugger::dump('foo2');
Debugger::barDump('foo3');
dump('bar');
\Tracy\Debugger::dump('bar2');
Debugger::barDump('bar3');
```

... outputs only bar `"bar"`.
 
Also, the Tracy bar doesn't show the following dumps section that `barDump() and bdump()` should show.
![tracy-dumps](https://cloud.githubusercontent.com/assets/5937902/16733820/a3b0d55c-4772-11e6-8997-97eaf32be417.png)

I'm using Laravel 5.1.40 in Laravel Homestead (PHP7).
Any more ideas what could be wrong? barDump() is very essential for printing variables in ajax requests and requests before redirecting.

**Comment by recca0120** [comment]
try 1.5.8

**Comment by recca0120** [comment]
@TeeJay-net 
I fix some bug today...

I install it in laravel 5.1
It's seems fine..

any question let me know ... thx

**Comment by TeeJay-net** [comment]
I've tried 1.5.8, still doesn't work as desired. 
Maybe it's something in my app, my homestead or maybe it's your package, I can't tell.
I don't know and it doesn't matter that much, I'll do fine with another debugbar and keep Tracy for my Nette projects.

Anyway, thanks for your time.

**Comment by recca0120** [comment]
okay...

maybe you have new project, you can try again XD

this is my screenshoot
![image 30](https://cloud.githubusercontent.com/assets/1390554/16777238/4935d526-489b-11e6-943e-78159bfa2710.png)
