### ISSUE TITLE
ajax capture stop working since 1.7.0

### ISSUE THREAD

**Issue by wppd** [recca0120/laravel-tracy#17]
so, from what I test, version 1.6.5 and 1.6.8 are working fine with ajax but it stops working since 1.7.0.

I'm using jquery and it's pretty simple.

`$.getJSON(url).done(function (resp) { })`

**Comment by recca0120** [comment]
my bad...

try 1.7.2

**Comment by wppd** [comment]
@recca0120 yep, it works now with 1.7.2. thanks!
