### ISSUE TITLE
How to disable on local env ?

### ISSUE THREAD

**Issue by sarfraznawaz2005** [recca0120/laravel-tracy#20]
Hi, I really like Tracy, thanks for porting it to laravel !

I tried below code in base controller and even in Exceptions/Handler.php to disable tracy if app is running in local mode:

````
if (!App::environment('local')) {
    Config::set('tracy.enabled', false);
}
````

However it didn't work.

Do you plan to add some `localOnly` option in package's config file ? Or how do I disable this on local for now ?

**Comment by shengyou** [comment]
Hi, you could consider to use `.env` to do this. For example, try to set `config/tracy.php` enabled using env helper like this:

```
<?php

return [
    'enabled' => env('APP_DEBUG', false),
];

```

then set your `.env` in your production server like this:

```
APP_DEBUG=false
```

tracy will disable when running on your production server. Hope this will help!

**Comment by sarfraznawaz2005** [comment]
oh yes it works, may be you should add that line in package itself. Thanks

**Comment by shengyou** [comment]
I had discuss with the package author before. After discussion, the author wants to leave this flexible for the package user. Every developer could deciese how to handle this by themselves.

**Comment by recca0120** [comment]
there are several ways to do this

you can do this too

```php
if (App::environment('local')) {
    App::register(Recca0120\LaravelTracy\ServiceProvider::class);
}
```

or

```php
return [
    'enabled' => env('APP_ENV') !== 'local',
];
```
