### ISSUE TITLE
Tracy debug config not working

### ISSUE THREAD

**Issue by magussiro** [recca0120/laravel-tracy#21]
目前我是改tracy.php

    'editor' => 'phpstorm://open?file=%file&line=%line',

但是跑出來的連結是'editor://
我去改Debgger.php 
line95    public static $editor = 'editor://open/?file=%file&line=%line';
才會連到我的IDE
其他的config 不太清楚有沒有影響

**Comment by tomaskazatel** [comment]
I have exactly the same problem. My Laravel App totaly ignore my config file. I cant switch to production mode.

**Comment by recca0120** [comment]
@magussiro 
是在standalone的狀態下
還是 Laravel內呢？

我的設定檔是用
'editor' => 'subl://open?url=file://%file&line=%line',
所出現的結果是

![image 2](https://cloud.githubusercontent.com/assets/1390554/19409058/9e929e0c-92fe-11e6-8d50-1c6a74f7c5b5.png)

**Comment by recca0120** [comment]
Hi @tomaskazatel 

I'm not sure I understand you question...

If you want tracy follow your .env file
like

APP_DEBUG=true

you need to change your tracy config file like

```

return [
    'enabled' => env('APP_DEBUG'),
    'showBar' => env('APP_DEBUG'),
    'useLavavelSession' => false,
    'accepts' => [
        'text/html',
    ],
    'editor' => 'subl://open?url=file://%file&line=%line',
    'maxDepth' => 4,
    'maxLength' => 1000,
    'scream' => true,
    'showLocation' => true,
    'strictMode' => true,
    'editorMapping' => [],
    'panels' => [
        'routing' => true,
        'database' => true,
        'view' => true,
        'event' => false,
        'session' => true,
        'request' => true,
        'auth' => true,
        'html-validator' => false,
        'terminal' => true,
    ],
];
```

**Comment by magussiro** [comment]
抱歉,是standalone
