### ISSUE TITLE
請問關於使用sentinel auth套件 在AuthPanel

### ISSUE THREAD

**Issue by imagine10255** [recca0120/laravel-tracy#24]
Hi 
我使用 [sentinel](https://cartalyst.com/manual/sentinel/2.0#introduction) 作為登入功能
可是在 AuthPanel 沒有顯示相關對應的登入資料

我試著在 /vendor/recca0120/laravel-tracy/src/Panels/AuthPanel.php @loadUser 修改了取得資訊的方式可以顯示, 但是這樣直接改了 vendor內的東西, 如果有更新版本, 就會被蓋掉, 請教是否有建議的方法呢 ?

**Comment by recca0120** [comment]
先建立一個 Imagine10255\AuthPanel.php
之後再到config/tracy.php新增

```php
   xxx
    'panels' => [
        'routing' => true,
        'database' => true,
        'view' => true,
        'event' => false,
        'session' => true,
        'request' => true,
        'auth' => true,
        'html-validator' => false,
        'terminal' => true,
        'Imagine10255\AuthPanel' => true,
    ],
```

或者也可以送 pr 再視情況合併

**Comment by imagine10255** [comment]
Hi 我有在本地新增了一個分支，加了 AuthSentinelPanel，但是這個分支推不上來

![image](https://cloud.githubusercontent.com/assets/5771353/22981313/0dc7d196-f3d7-11e6-8340-1e192286118f.png)

![image](https://cloud.githubusercontent.com/assets/5771353/22981346/280fce46-f3d7-11e6-9c80-3d5acf1fd22e.png)

**Comment by recca0120** [comment]
你有 fork 這個專案
先 clone 自己的專案，
在自己的 github 上修改，
最後再送 pr

**Comment by imagine10255** [comment]
Hi 我送了 pr

**Comment by recca0120** [comment]
Hi
把 composer.json 改為
```json
    "recca0120/laravel-tracy": "dev-sentinel"
```

試看看能不能正常運作，可以的話就正式放出支援 sentinel 的版本

**Comment by imagine10255** [comment]
HI 我將 composer.json 改了, 但似乎回報 dev-master 版本不存在

![image](https://cloud.githubusercontent.com/assets/5771353/23284520/f8ecbfe8-fa66-11e6-8fce-eab0241b3f00.png)

![image](https://cloud.githubusercontent.com/assets/5771353/23284495/db7a0ed4-fa66-11e6-893a-c94846f6382a.png)

**Comment by recca0120** [comment]
```json
"laravel-tracy": "dev-master as v1.7.x-dev"
```

**Comment by imagine10255** [comment]
目前測試沒有問題
