### ISSUE TITLE
How do set an email address for alerts in the config

### ISSUE THREAD

**Issue by alexryderwhytewaters** [recca0120/laravel-tracy#27]
Normally with tracy i set it up like this

Debugger::enable(Debugger::DETECT, 'logs/tracy', 'alertemail@invalid');
Debugger::getLogger()->emailSnooze = 30; 

How can I configure those settings in the config.php?

**Comment by recca0120** [comment]
Hello
It doesn't work in laravel

but you can try this
http://stackoverflow.com/questions/33163893/laravel-5-send-errors-to-email

Maybe I'll make this happen, when I have time...

**Comment by recca0120** [comment]
hi @alexryderwhytewaters 

can you tell me, how does emailSnooze work ???
when exception happen, mail exception message to you ???

**Comment by bumperbox** [comment]
emailSnooze is the time between error emails being sent, so that you don't get flooded with error emails if you create a bug on your website

This is the default setting

/** @var mixed interval for sending email is 2 days */
public $emailSnooze = '2 days';
