### ISSUE TITLE
Debugger bar not showing at all

### ISSUE THREAD

**Issue by janwehner** [recca0120/laravel-tracy#33]
I'm having trouble getting the debug bar running.

Versions:
Laravel: 5.4.23
Laravel-Tracy: 1.8.5
Tracy: 2.4.6

I've installed the package as given in the Readme. I can use the dump()/bdump() methods and they're working correctly. But I can't see the debugger bar. I can see that the javascript file is loaded and even the div is shown but not the bar. You got any advice?

```
<!-- Tracy Debug Bar -->
<div id="tracy-debug" data-id="76112ef7ec" data-nonce=""></div>
<script src="?_tracy_bar=content.76112ef7ec&amp;XDEBUG_SESSION_STOP=1"></script>
```

Tracy config:
```
<?php

return [
    'enabled' => env('APP_DEBUG') === true,
    'showBar' => env('APP_ENV') !== 'production',
    'accepts' => [
        'text/html',
    ],
    'appendTo' => 'body',
    'editor' => 'subl://open?url=file://%file&line=%line',
    'maxDepth' => 4,
    'maxLength' => 1000,
    'scream' => true,
    'showLocation' => true,
    'strictMode' => true,
    'editorMapping' => [],
    'panels' => [
        'routing' => true,
        'database' => true,
        'view' => true,
        'event' => false,
        'session' => true,
        'request' => true,
        'auth' => true,
        'html-validator' => false,
        'terminal' => true,
    ],
];
```

**Comment by recca0120** [comment]
Open chrome dev panel
Click network tab
Does it show any errors???

**Comment by janwehner** [comment]
No errors showing. But I found out that in the Javascript file which gets generated there is an initialization part at the end but this part is missing in my file. But I can't figure out why it's not get generated.
