### ISSUE TITLE
Tracy Handler.php render method checks if response->getContent instance of View, but is string so never returns view.

### ISSUE THREAD

**Issue by jrbarnard** [recca0120/laravel-tracy#36]
In Laravel 5.4, if in my exception handler I add some code like:

`
return response()->view('errors.403', [], 403);
`
And have Tracy running, tracy will never show the view response and instead shows the full exception trace, this is because in: vendor/recca0120/laravel-tracy/src/Exceptions/Handler.php Line 62, we check $response->getContent instanceof View, however at this point the getContent returns the compiled view string, and it's the original property on the response that holds the view instance.

We could add an additional || to the if to account for $response->getOriginalContent() instanceof View (Looking at the commit history of the Response class in Laravel, when setting content it always rendered the view object into a string so it may be this never worked and we should either be checking is_string or checking the originalContent?)

**Comment by recca0120** [comment]
![1](https://user-images.githubusercontent.com/1390554/28329336-13466d22-6c1c-11e7-99b1-abe2b358f47a.jpg)

Hi @jrbarnard 

when I return response()->view('errors.403', [], 403), It work correctly. (like this screenshot)
could you show me. this full exception trace ??

and check $response->getContent();
https://github.com/laravel/framework/blob/5.4/src/Illuminate/Routing/ResponseFactory.php#L69
https://github.com/laravel/framework/blob/5.4/src/Illuminate/View/Factory.php#L123
use response()->view('errors.403', [], 403) will return View.

and $response->getOriginalContent(), it only work on JsonResponse.

**Comment by jrbarnard** [comment]
Hi @recca0120 

Re reading the issue I added and I definitely wasn't very clear! Hopefully the below helps to show the issue.

Throwing an exception say in a controller (this example is basically mocking a policy exception):
<img width="683" alt="screen shot 2017-07-18 at 21 58 17" src="https://user-images.githubusercontent.com/6758366/28339507-387122d0-6c04-11e7-95cf-b499e7e04710.png">

It will be handled as expected in app/Exceptions/Handler.php in the render method. If I say check for the type of the exception and then say handle the response in a specific way, this example is a policy exception has occurred therefore we will show the errors.403 view:
<img width="500" alt="screen shot 2017-07-18 at 22 00 13" src="https://user-images.githubusercontent.com/6758366/28339595-7e6a3948-6c04-11e7-9ca7-1c51688a1400.png">

However, we get the full tracy exception trace like below:
<img width="1265" alt="screen shot 2017-07-18 at 22 01 37" src="https://user-images.githubusercontent.com/6758366/28339640-b033ccd2-6c04-11e7-8f5b-9c22adbb2425.png">

Instead of the expected 403 view.

It's definitely hitting the response()->view code in Handler.php, however as the tracy Handler overrides this handler and then runs checks on the response from our Handler.php render method, tracy doesn't return the response as expected as '$response->getContent() instanceof View' doesn't evaluate to true.

Let me know if you're having any trouble recreating the issue, I can make a pull request for a potential fix if needed?

Cheers,
James

**Comment by jrbarnard** [comment]
I've added a pull request [here](https://github.com/recca0120/laravel-tracy/pull/37) to fix this issue, it keeps the old $response->getContent() check, but also adds an original content comparison as all laravel response views content are strings by the time the response is inspected.

**Comment by jrbarnard** [comment]
@recca0120 Thanks for merging the pull request are we able to do a 1.8.91 release to packagist with the fix so I can update via composer using tagged releases?

**Comment by recca0120** [comment]
release
