### ISSUE TITLE
Is it possible to cancel the Bar render for specific routes?

### ISSUE THREAD

**Issue by jonphipps** [recca0120/laravel-tracy#40]
I have some routes that should not show the Tracy Bar.
These are normal html routes, not ajax, but I need to turn off Tracy as if the request was ajax.

Is there a way to do that for specific routes in middleware?

And thank you for maintaining this. I find Tracy to be more useful than Laravel Debugbar, and much faster.

**Comment by recca0120** [comment]
Hi @jonphipps 
when send ajax, you need set header 'X-Requested-With'
tracy will trun off

see http://en.wikipedia.org/wiki/List_of_Ajax_frameworks#JavaScript
