### ISSUE TITLE
Error in Auth showing at AJAX bar

### ISSUE THREAD

**Issue by littpi** [recca0120/laravel-tracy#41]
When there are AJAX events occur, the AJAX bar will appear. However, the "User" attribute of the AJAX bar shows "Error in Auth". I have clicked it and it throws the exceptions inside the modal window.

![fireshot screen capture 001 - i i - littpi_cool_admin_user_group](https://user-images.githubusercontent.com/17842734/37892096-38934dd6-3109-11e8-9d28-5d83785f57ca.png)

**Comment by recca0120** [comment]
is your auth driver token driver ???

if yes, I'll fix this bug..
if no. tell me, what is your auth driver

**Comment by recca0120** [comment]
this bug is fixed.

you can try again

**Comment by littpi** [comment]
Wanna tell you I am using the token driver but you have fixed it already. lol

Thanks, it works. :)
![image](https://user-images.githubusercontent.com/17842734/37899691-d8285930-311e-11e8-9608-81abfa375cc3.png)
