### ISSUE TITLE
Enable tracy bar, but disable error page. Possible?

### ISSUE THREAD

**Issue by martinandersen3d** [recca0120/laravel-tracy#42]
Hi, I like the Tracy bar. And the view tab is awesome.

But I would like to use Laravel standart error reporting. Can I disable the error reporting from Laravel-Tracy and still keep the Tracy bar (with the view tab) ? :) Thanks

**Comment by recca0120** [comment]
@martinandersen3d 

you can set "showException" => false in config file to disable execption
