### ISSUE TITLE
1.8.21在 laravel 5.8好像也是錯誤耶...

### ISSUE THREAD

**Issue by eric2100** [recca0120/laravel-tracy#46]
File: .../src/Middleware/RenderBar.php:93

83:            $this->debuggerManager->dispatch();
84:    
85:            $response = $next($request);
86:    
87:            $ajax = $request->ajax();
88:    
89:            if ($this->reject($response, $request, $ajax) === true) {
90:                return $response;
91:            }
92:    
93:            $this->events->fire(new BeforeBarRender($request, $response));
94:    
95:            $response->setContent(
96:                $this->debuggerManager->shutdownHandler(
97:                    $response->getContent(), $ajax

**Comment by recca0120** [comment]
已修復
