### ISSUE TITLE
Use Tracys dump-function without typing FQN \Tracy\Debugger::dump

### ISSUE THREAD

**Issue by nemethit** [recca0120/laravel-tracy#49]
Is it possible to use Tracy's own **dump-function** without the full class-location `\Tracy\Debugger::dump($putYourVariableHere);` in Laravel?

I understand that currently symfonys dump-function getting called when typing just `dump($putYourVariableHere);` but it would nicer to call Tracy ones instead, because of:
- Used old `dump` command (it is just shorter to type)
- Tracy responses the File-Path (with editor-link)

Sure we could just use `bdump` the whole time instead, but would lose the common old dump in page. And to wrap another function around a `Tracy-Debbuger::dump` is also a bad idea, because the dumped-file position would be always the wrapper-function then.

**Comment by recca0120** [comment]
bdump($variable)
