### ISSUE TITLE
Incompatibility with Laravel 6

### ISSUE THREAD

**Issue by tommym9** [recca0120/laravel-tracy#55]
Laravel version: v6.18.8
Laravel Tracey: v1.11.0
PHP: PHP 7.2

Declaration of Recca0120\LaravelTracy\Exceptions\Handler::report(Throwable $e) must be compatible with Illuminate\Contracts\Debug\ExceptionHandler::report(Exception $e)

Looks like Recca0120\LaravelTracy\Exceptions\Handler.php report and render methods need to be updated to be compatible with the Laravel 6 version.

Cheers

Tom

**Comment by recca0120** [comment]
fixed
