### ISSUE TITLE
更新 php 8.1後，DatabasePanel發生error錯誤訊息

### ISSUE THREAD

**Issue by eric2100** [recca0120/laravel-tracy#59]
ErrorException: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /vendor/recca0120/laravel-tracy/resources/views/DatabasePanel/panel.php:59
Stack trace:
#0 [internal function]: Tracy\Bar->Tracy\{closure}()
#1 /vendor/recca0120/laravel-tracy/resources/views/DatabasePanel/panel.php(59): htmlspecialchars()
#2 /vendor/recca0120/laravel-tracy/src/Template.php(58): require('/home/www3/publ...')
#3 /vendor/recca0120/laravel-tracy/src/Panels/AbstractPanel.php(111): Recca0120\LaravelTracy\Template->render()
#4 /vendor/recca0120/laravel-tracy/src/Panels/AbstractPanel.php(83): Recca0120\LaravelTracy\Panels\AbstractPanel->render()
#5 /vendor/tracy/tracy/src/Tracy/Bar/Bar.php(150): Recca0120\LaravelTracy\Panels\AbstractPanel->getPanel()

**Comment by recca0120** [comment]
fixed
