### ISSUE TITLE
recca0120/terminal

### ISSUE THREAD

**Issue by killtw** [recca0120/laravel-tracy#8]
建議是把 recca0120/terminal 改成 suggests 而不是直接放在 require 裡頭
畢竟不是每個人都會需要這個功能

**Comment by recca0120** [comment]
將terminal從suggests移到require
是希望能讓它多一點特色
而且可以讓想要使用完整功能的人
減少設定上的複雜度

不過也有考量到不需要的狀況
只要到config下設定
```php
"panels" => [
    "terminal" => false
]
```
就可以完全取消該功能

**Comment by killtw** [comment]
可是這樣變成不需要的人在 composer install 的時候還是會需要花時間去下載 terminal

**Comment by recca0120** [comment]
確實是會多花費時間下載
不過以terminal的package來看
幾乎都是laravel內建
抓下它的zip檔也不到200k（實際上會使用到的檔案應該不到100k）
下載200k所需的時間應該很短才是
再加上composer安裝也會透過快取
下載時間的影響不大才是

就目前為止希望能再增加laravel-tracy及terminal的功能
而不要減少掉它的功能

如果有需要什麼功能是必須的可以提出來討論囉
