### ISSUE TITLE
HttpResponseException when FormRequest fails validation

### ISSUE THREAD

**Issue by xexperimente** [recca0120/laravel-tracy#9]
Laravel 5.2.21, laravel-tracy 1.4.1

When I use FormRequest validation and it failed, instead of redirect i get this exception

Thrown from  ...\src\Illuminate\Foundation\Http\FormRequest.php:97

```
protected function failedValidation(Validator $validator)
{
            throw new HttpResponseException($this->response(
                $this->formatErrors($validator)
           ));
}
```

When I turn of laravel-tracy everything works fine.

**Comment by recca0120** [comment]
ok I will fix it

**Comment by xexperimente** [comment]
thanks
